// This query is too long to be in an Analytics Rule (more than 10.000 characters), so it had to be made a function that can be called by the rule.
// You can find the function in the next link, just try to define "query_frequency", "query_period" and "query_wait".
//
// https://github.com/ep3p/Sentinel_KQL/blob/main/Functions/Analytics-UnexpectedEntraIDDevice.kql
//
UnexpectedEntraIDDevice(query_frequency = 1h, query_period = 14d, query_wait = 1h)
