Anomalies
| where RuleName endswith "Attempted computer bruteforce" and RuleStatus != "Flighting"
| extend
    Query = ExtendedLinks[0]["DetailBladeInputs"],
    Computer = Entities[0]["HostName"],
    AttemptCount = toint(AnomalyDetails["Observables"][0]["Value"])
| project
    TimeGenerated,
    RuleName,
    Description,
    Query,
    Computer,
    AttemptCount,
    Score,
    AnomalyDetails,
    Entities,
    Tactics
