Anomalies
| where RuleName endswith "Suspicious volume of failed login attempts to AWS Console by each source IP address" and RuleStatus != "Flighting"
| extend
    Query = ExtendedLinks[0]["DetailBladeInputs"],
    AttemptCount = toint(AnomalyDetails["Observables"][0]["Value"])
| project
    TimeGenerated,
    RuleName,
    Description,
    Query,
    AttemptCount,
    Score,
    AnomalyDetails,
    Entities,
    Tactics,
    Techniques,
    ExtendedLinks
