DeviceTvmSoftwareVulnerabilities
//| where SoftwareName has_any ("chrome", "edge", "cortex", "windows")
//| where CveId has_any ("CVE-2021-29358", "CVE-2021-29359")
//| where VulnerabilitySeverityLevel has_any ("Low", "Medium", "High", "Critical")
| summarize CveIdList = make_list(bag_pack("CveId", CveId, "VulnerabilitySeverityLevel", VulnerabilitySeverityLevel, "RecommendedSecurityUpdate", RecommendedSecurityUpdate)), take_any(DeviceName, OSPlatform, OSVersion, OSArchitecture) by DeviceId, SoftwareName, SoftwareVersion
| summarize Vulnerabilities = make_list(bag_pack("SoftwareName", SoftwareName, "SoftwareVersion", SoftwareVersion, "CVEs", CveIdList)), take_any(DeviceName, OSPlatform, OSVersion, OSArchitecture) by DeviceId
| project DeviceName, Vulnerabilities, OSPlatform, OSVersion, OSArchitecture, DeviceId
//| limit 100
